# Generated by Django 3.2.7 on 2021-09-29 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('thumbnail_path_text', models.CharField(max_length=255)),
                ('html_text', models.TextField()),
                ('created_date', models.DateTimeField()),
                ('minutes_to_read', models.IntegerField(default=0)),
            ],
        ),
    ]
