name: BUILD
on:
  push:
    branches: main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Lint and tests"
      - run: docker-compose run app sh -c python "manage.py test && flake8"
