name: BUILD
on:
  push:
    branches: main
  workflow_dispatch:
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: "Lint and tests"
      - run: docker-compose run app sh -c python "manage.py test && flake8"
