name: BUILD
on:
  push:
    branches: dev
  workflow_dispatch:
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: "Lint and tests"
        run: echo ok
        #run: docker-compose -f "docker-compose.yml" run app sh -c "python manage.py test && flake8"
